export type ProductKey = 'LD%' | 'SD%';

export type ViewName =
  | 'Top_Left_View'
  | 'Top_Right_View'
  | 'Back_View'
  | 'Left_View'
  | 'Bottom_View'
  | 'Right_View'
  | 'Corner_View';

export type ViewZonesType = Record<ProductKey, Record<ViewName, string[]>>;

export const ViewZones: ViewZonesType = {
  'LD%': {
    Top_Left_View: [
      'FL 1 LH',
      'HX',
      'HY',
      'HZ',
      'FL 1 RH',
      'A1',
      'D1',
      'X1',
      'Y1',
      'Z1',
      'B1',
      'E1',
      'U1',
      'V1',
      'Ñ2',
      'Q2',
      'C1',
      'F1',
      'R1',
      'S1',
      'N2',
      'P2',
      'HC 1 LH',
      'G1',
      'J1',
      'H1',
      'K1',
      'I1',
      'I1',
      'M2',
      'O2',
    ],
    Top_Right_View: [
      'FL 1 LH',
      'HX',
      'HY',
      'HZ',
      'FL 1 RH',
      'X1',
      'Y1',
      'Z1',
      'Q1',
      'Ñ1',
      'D2',
      'A2',
      'V1',
      'W1',
      'P1',
      'N1',
      'E2',
      'B2',
      'S1',
      'T1',
      'O1',
      'M1',
      'F2',
      'C2',
      'K1',
      'L1',
      'G1',
      'H1',
      'I1',
      'HC 1 RH',
    ],
    Back_View: ['HC 2 RH', 'I2', 'L2', 'H2', 'K2', 'G2', 'J2', 'HC 2 LH'],
    Left_View: ['Ñ2', 'Q2', 'N2', 'P2', 'M2', 'O2'],
    Bottom_View: ['T2', 'S2', 'R2', 'W2', 'V2', 'U2', 'Z2', 'Y2', 'X2'],
    Right_View: ['C2', 'F2', 'B2', 'E2', 'A2', 'D2'],
    Corner_View: ['HC 2 RH', 'HC 2 LH'],
  },
  'SD%': {
    Top_Left_View: [
      'HX',
      'HY',
      'HZ',
      'A1',
      'D1',
      'X1',
      'Y1',
      'Z1',
      'Ñ2',
      'Q2',
      'B1',
      'E1',
      'U1',
      'V1',
      'N2',
      'P2',
      'C1',
      'F1',
      'R1',
      'S1',
      'M2',
      'O2',
      'C1',
      'F1',
      'R1',
      'S1',
      'HC 1 LH',
      'G1',
      'J1',
      'H1',
      'K1',
      'I1',
    ],
    Top_Right_View: [
      'HX',
      'HY',
      'HZ',
      'D2',
      'A2',
      'Y1',
      'Z1',
      'Q1',
      'Ñ1',
      'E2',
      'B2',
      'V1',
      'W1',
      'P1',
      'N1',
      'F2',
      'C2',
      'S1',
      'T1',
      'O1',
      'M1',
      'G1',
      'H1',
      'K1',
      'I1',
      'L1',
      'HC 1 RH',
    ],
    Back_View: ['HC 2 RH', 'I2', 'L2', 'H2', 'K2', 'G2', 'J2', 'HC 2 LH'],
    Left_View: ['Ñ2', 'Q2', 'N2', 'P2', 'M2', 'O2'],
    Bottom_View: ['T2', 'S2', 'R2', 'W2', 'V2', 'U2', 'Z2', 'Y2', 'X2'],
    Right_View: ['C2', 'F2', 'B2', 'E2', 'A2', 'D2'],
    Corner_View: ['HC 2 RH', 'HC 2 LH'],
  },
};
